# Generated by Django 5.0.1 on 2024-01-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('price', models.IntegerField(max_length=35)),
                ('path_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('price', models.IntegerField(max_length=35)),
                ('path_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('price', models.IntegerField(max_length=35)),
                ('path_img', models.TextField()),
            ],
        ),
    ]
